{
  config,
  pkgs,
  ...
}: {
  # Import other configuration modules
  # (hardware-configuration.nix is autogenerated upon installation)
  # paths in nix expressions are always relative the file which defines them

  nix.settings.experimental-features = ["nix-command" "flakes"];

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  services.logind.extraConfig = ''
    HandleLidSwitch=ignore
    HandleLidSwitchDocked=ignore
    HandleLidSwitchExternalPower=ignore
  '';

  imports = [
    ./hardware_configuration.nix
    ./containers/pihole.nix
  ];

  # Name your host machine
  networking.hostName = "homelab";

  # Set your time zone.
  time.timeZone = "Europe/London";

  # Enter keyboard layout
  services.xserver.layout = "us";

  # Vvirtualisation
  virtualisation.docker = {
    enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Define user accounts
  users.users.eve = {
    extraGroups = ["wheel" "networkmanager" "docker"];
    isNormalUser = true;
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIA2bnr88G2H2/BnK4U7zvIqOv+x2GbkWJuWnFYuyXbFP"
    ];
  };

  # Install some packages
  environment.systemPackages = with pkgs; [
    docker
    helix
    git
    github-cli
    networkmanager
    zellij
  ];

  networking.networkmanager.enable = true;
  services.dbus.enable = true;
  # Enable the OpenSSH daemon
  services.openssh.enable = true;
  services.openssh.settings.PasswordAuthentication = true;
}
